public class AP00_UtilityConstants {

    public static final String BADGE_ACCOUNT_CREATION = 'Account Creation';
    public static final String BADGE_OPPORTUNITY_CREATION = 'Opportunity Creation';
    public static final String BADGE_CONTACT_CREATION = 'Contact Creation';
    public static final String BADGE_CONTACT_UPDATE = 'Contact Update';
    public static final String BADGE_QUOTE_COPY = 'Copy Quote';
    public static final String BADGE_LEAD_CONVERSION = 'Lead Conversion';
    public static final String BADGE_LEAD_CREATION = 'Lead Creation';
    public static final String BADGE_LEAD_UPDATE = 'Lead Update';
    public static final String BADGE_EVENT_CREATION = 'Event Creation';
    public static final String BADGE_TASK_CREATION = 'Task Creation';
    public static final String BADGE_LOG_CALL = 'Call Log';
    public static final String BADGE_CHATTER_POST_COMMENT = 'Chatter Comments Posts';
    public static final String CONTACT_CONTACT_TYPE_USER = 'User';
    public static final String ACCOUNT_GAMIFICATION_ACCOUNT_NAME = 'GAMEACCOUNT';
    public static final String FINEMIST_PRODUCTSEGMENT_NAME = 'Fine mist pumps';
    
    public static final Set<String> LEAD_PRODUCTLINE_TUBE = new Set<String>{'Tubes'};
    public static final Set<String> LEAD_PRODUCTLINE_CRP = new Set<String>{'Mascara, Eyeliner, Lipgloss, Brows & Nails', 'Lipsticks & Sticks','Compacts & Palettes','Skin care Caps, Jars & Bottles'};
    public static final Set<String> LEAD_PRODUCTLINE_DISPENSING = new Set<String>{'Lotion Pumps', 'Fragrance Caps', 'Foam Pumps'};
    public static final Set<String> LEAD_PRODUCTLINE_BEAUTYSOLUTIONS = new Set<String>{'Cosmetic Accessories', 'Cosmetic Turnkey Solutions', 'Gifts, Kits & Retail', 'Travel & Sports'}; 

    public static final Set<String> LEAD_PRODUCTLINE_TUBESS = new Set<String>{'Tubes','Fast-Track Tubes'};
    public static final Set<String> LEAD_PRODUCTLINE_CRPSS = new Set<String>{'Mascara, Eyeliner, Brows, Gloss & Nails', 'Eyeliner','Lipgloss','Lipsticks', 'Compacts & Palettes','Sticks','Jars & Bottles', 'Fragrance & Skin Care Caps'};
    public static final Set<String> LEAD_PRODUCTLINE_BEAUTYSOLUTIONSSS = new Set<String>{'Cosmetic Accessories', 'Cosmetic Turnkey Solutions', 'Gifts, Retail Solutions & Kitting'};    
        
        
}